spring.application.name=LojaCarro

spring.profiles.active=${SERVER}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false

ratelimit.max-requests=100
ratelimit.window-seconds=60
